/*
 * notices.js: disclaimers and attribution, kept in one place so the same
 * wording appears everywhere (app, exports, report). Short versions go in
 * small print next to generated content; full versions fill the About panel.
 */
(function () {
  'use strict';

  var N = {};

  // --- Short versions -----------------------------------------------------
  N.REPORT_SMALL_PRINT =
    'Prepared with the CAPE-Vr Clinical Acoustic Reporting Tool (CART), a documentation aid; it does not diagnose. ' +
    'Acoustic values depend on recording conditions, equipment, and analysis settings. ' +
    'Any categories or reference values are clinic-defined. Interpretation is the clinician’s responsibility.';
  N.SUMMARY_SHORT = 'Generated by rules from the entered scores and clinic-defined settings. Review and edit before use. Not a diagnosis.';
  N.EMR_SHORT = 'Rule-based draft from the entered scores and clinic-defined settings. Review and edit before clinical use. Not a diagnosis.';
  N.ACOUSTIC_SHORT = 'Acoustic results depend on recording conditions, equipment, and the analysis settings chosen. Verify them in your own workflow.';
  N.CSV_SHORT = 'Contains identifying information unless “CSV without names” is ticked. Values are as entered or as reported by Praat.';
  N.REFERENCE_SHORT = 'Reference values are clinic-defined. The software does not provide normative values or confirm that a value is clinically valid.';

  // --- Full versions (About panel) ---------------------------------------
  N.FULL = [
    ['Intended use',
      'This software helps clinicians organize, document, and report a CAPE-Vr evaluation and an optional acoustic analysis run in Praat. ' +
      'It does not diagnose disorders and does not replace clinical judgment. Clinical interpretation remains the responsibility of the clinician.'],
    ['Acoustic analysis',
      'Acoustic measures are computed by Praat, run by the user, with the procedures and settings selected in this tool. ' +
      'Results may vary with recording conditions, microphone characteristics, signal quality, analysis settings, preprocessing procedures, and software versions. ' +
      'Users are responsible for verifying acoustic outputs against their own workflows and requirements.'],
    ['Generated text',
      'Summaries, documentation drafts, and patterns are produced by fixed, visible rules from the entered scores, the values reported by Praat, and clinic-defined settings. ' +
      'No other logic is used. Generated text should be reviewed and edited before clinical use.'],
    ['Reference values and ranges',
      'Any reference values, ranges, or category labels are defined and configured by the clinic. ' +
      'The software does not determine normative values and does not claim that any threshold, range, or label is clinically valid.'],
    ['Data and privacy',
      'Session files, packages, reports, and CSV files may contain identifying information and voice recordings. They are saved only where you choose. ' +
      'Store and share them according to your organization’s policies. The “hide names” options remove selected fields only; they are not a full de-identification.'],
    ['Liability',
      'The software provides organizational and reporting assistance only, and is provided as is, without warranty of any kind.']
  ];

  // --- Attribution (required by the CC BY 4.0 license) --------------------
  N.ATTRIBUTION = [
    'This tool implements a documentation workflow around the Consensus Auditory-Perceptual Evaluation of Voice – Revised (CAPE-Vr): ' +
      'Kempster GB, Nagle KF, Solomon NP. Development and rationale for the Consensus Auditory-Perceptual Evaluation of Voice—Revised (CAPE-Vr). ' +
      'Journal of Voice (2025). doi:10.1016/j.jvoice.2025.01.022.',
    'The CAPE-Vr form content, stimuli, and Table 1 instructions are reproduced and adapted from that article under the Creative Commons Attribution 4.0 International license (CC BY 4.0, creativecommons.org/licenses/by/4.0). ' +
      'Changes: the form is presented electronically, with one “examiner modeled” box per sentence, the option to add further named attribute scales below the blank one, and marked app notes.',
    'The CAPE-Vr revises the original CAPE-V (Kempster GB, Gerratt BR, Verdolini Abbott K, Barkmeier-Kraemer J, Hillman RE. Am J Speech Lang Pathol 2009;18:124–132; ' +
      'developed under ASHA Special Interest Division 3). The original CAPE-V forms are not reproduced here.',
    'This tool is independent. It is not affiliated with, endorsed by, or produced by the CAPE-Vr or CAPE-V authors, the American Speech-Language-Hearing Association, The Voice Foundation, or Elsevier.',
    'Praat (Boersma P, Weenink D; praat.org) is separate software, run by the user. It is not included in or distributed with this tool.'
  ];
  N.ATTRIBUTION_SHORT = 'CAPE-Vr: Kempster, Nagle & Solomon (2025), J Voice, doi:10.1016/j.jvoice.2025.01.022; form content adapted under CC BY 4.0. ' +
    'This tool is independent and not affiliated with or endorsed by the CAPE-Vr authors, ASHA, or the publisher.';

  // Elements with data-notice="KEY" get N[KEY], so HTML never duplicates wording.
  N.render = function () {
    var about = document.getElementById('about-body');
    if (about && !about.childNodes.length) {
      N.FULL.forEach(function (x) {
        var h = document.createElement('h3');
        h.textContent = x[0];
        var p = document.createElement('p');
        p.textContent = x[1];
        about.appendChild(h);
        about.appendChild(p);
      });
      var h = document.createElement('h3');
      h.textContent = 'Attribution';
      about.appendChild(h);
      N.ATTRIBUTION.forEach(function (t) {
        var p = document.createElement('p');
        p.textContent = t;
        about.appendChild(p);
      });
    }
    Array.prototype.forEach.call(document.querySelectorAll('[data-notice]'), function (el) {
      el.textContent = N[el.getAttribute('data-notice')] || '';
    });
  };

  window.CapeNotices = N;
})();
